Added codecarbon tracking to Simvue Run
simvue-io/python-api pull request #508
Opened 2024-09-09 14:34 UTC by kzscisoft

Uses [Code Carbon](https://github.com/mlco2/codecarbon) to track emissions during a Simvue run, this can be disabled via the `config` method.

2024-09-11 14:29 UTC, wk9874 requested changes

2024-09-12 14:10 UTC, kzscisoft commented on simvue/eco.py
> +        if self._meta_update:
Yes I missed `self._meta_update = False`

2024-09-12 14:17 UTC, kzscisoft commented on simvue/eco.py
> +            measure_power_secs=0.1,
The high abundance of API calls is handled by the dispatcher but we can add this as an option and I think the default should be the same as resource metrics interval which is the heartbeat rate of 60s

2024-09-12 14:21 UTC, alahiff commented on simvue/eco.py
> +            measure_power_secs=0.1,
Is this really collecting emissions data every 0.1 secs? What is the value of collecting it so often? I assume this must be a mistake?

2024-09-12 14:23 UTC, kzscisoft commented on simvue/eco.py
> +            allow_multiple_runs=False,
Done

2024-09-13 05:44 UTC, alahiff commented
The names of the metrics are possibly not compatible with the standard way "magic" metrics grouping works in the UI. By default the following will be grouped:
* codecarbon.emissions.delta, codecarbon.emissions.total
* codecarbon.energy_consumed.delta, codecarbon.energy_consumed.total

Does it make sense for deltas and totals to be displayed together?

2024-09-13 05:45 UTC, alahiff commented
Is it possible to suppress this message to stdout?
```
[codecarbon WARNING @ 05:39:03] Multiple instances of codecarbon are allowed to run at the same time.
```
I also get this warning now when running the client:
```
/home/alahiff/.cache/pypoetry/virtualenvs/simvue-0vzJveOR-py3.10/lib/python3.10/site-packages/codecarbon/output_methods/file.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(total.values)])])
```

2024-09-13 05:55 UTC, alahiff commented
When running this for 180 seconds I only get a single set of codecarbon metrics at the very end. Is this expected?

2024-09-23 15:06 UTC, AbyAbraham21 commented
"Keep emissions data off by default" - Why? I would assume you want it on by default?

2024-09-24 12:31 UTC, kzscisoft commented
@AbyAbraham21 Due to the fact that setup is required on the host machine for the CC metrics to be valid and correct we should make the user accountable for their recording as opposed to it being our responsibility that their setup is correct. @alahiff and I agreed having these off by default made sense.

We will of course need to document enabling the feature.

2024-09-24 13:13 UTC, merged